/**
 * Sample portfolio for UI work without a token or a network.
 *
 * Enabled only when BOTH hold: this is a development build (__DEV__), and
 * the bundle was started with EXPO_PUBLIC_SAMPLE_DATA=1. A release build can
 * never show it, and the app labels every screen "Sample data" while it is
 * on, so it cannot be mistaken for the real portfolio.
 *
 *   EXPO_PUBLIC_SAMPLE_DATA=1 npx expo start
 *
 * Figures are generated by a seeded random walk, so they are stable between
 * reloads but are not real prices and not real results.
 */

import { PendingBuy, Position, SleeveState, Trade } from '../types';

export const SAMPLE_MODE: boolean =
  typeof __DEV__ !== 'undefined' && __DEV__ && process.env.EXPO_PUBLIC_SAMPLE_DATA === '1';

/** Deterministic PRNG (mulberry32) so the sample looks the same every launch. */
function rng(seed: number) {
  return () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function sessions(start: string, count: number): string[] {
  const out: string[] = [];
  const d = new Date(`${start}T00:00:00Z`);
  while (out.length < count) {
    const dow = d.getUTCDay();
    if (dow !== 0 && dow !== 6) out.push(d.toISOString().slice(0, 10));
    d.setUTCDate(d.getUTCDate() + 1);
  }
  return out;
}

type Seed = [ticker: string, entry: number, sector: string];

function build(opts: {
  capital: number;
  start: string;
  count: number;
  seed: number;
  drift: number;
  held: Seed[];
  /** Share of capital put into the held names. */
  deploy?: number;
  unmarked?: number;
  pending?: [string, number, number, string][];
  sold?: [string, number, number, number, string][];
  startKey: 'trial_start_date' | 'trial_v2_start_date';
}): SleeveState {
  const rand = rng(opts.seed);
  const dates = sessions(opts.start, opts.count);
  const last = dates[dates.length - 1];
  const perName = (opts.capital * (opts.deploy ?? 0.92)) / opts.held.length;

  const positions: Record<string, Position> = {};
  const trades: Trade[] = [];
  let invested = 0;

  opts.held.forEach(([ticker, entry, sector], i) => {
    const qty = Math.max(1, Math.floor(perName / entry));
    const move = 1 + opts.drift + (rand() - 0.42) * 0.22;
    const marked = i < opts.held.length - (opts.unmarked ?? 0);
    const cost = qty * entry;
    invested += cost;
    positions[ticker] = {
      ticker,
      entry_date: dates[Math.min(2 + i, dates.length - 1)],
      entry_price: entry,
      entry_atr: entry * 0.02,
      quantity: qty,
      stop_loss: +(entry * 0.9).toFixed(2),
      take_profit: 0,
      trailing_stop: +(entry * move * 0.93).toFixed(2),
      highest_since_entry: +(entry * Math.max(move, 1)).toFixed(2),
      invested: cost,
      entry_costs: +(cost * 0.00118).toFixed(2),
      sector,
      ...(marked ? { last_price: +(entry * move).toFixed(2), last_price_date: last } : {}),
    };
    trades.push({
      ticker, action: 'BUY', date: positions[ticker].entry_date, price: entry,
      quantity: qty, notional: cost, costs: +(cost * 0.00118).toFixed(2),
      reason: 'Entered on rebalance', pnl_gross: 0, pnl_net: 0,
    });
  });

  for (const [ticker, entry, exit, qty, reason] of opts.sold ?? []) {
    const gross = (exit - entry) * qty;
    trades.push({
      ticker, action: 'SELL', date: dates[dates.length - 6], price: exit, quantity: qty,
      notional: exit * qty, costs: +(exit * qty * 0.0012 + 15.93).toFixed(2), reason,
      pnl_gross: gross, pnl_net: +(gross - exit * qty * 0.0024 - 15.93).toFixed(2),
    });
  }
  trades.sort((a, b) => a.date.localeCompare(b.date));

  const realised = trades.reduce((a, t) => a + (t.action === 'SELL' ? t.pnl_net ?? 0 : 0), 0);
  const cash = opts.capital - invested + realised;
  const finalMtm = Object.values(positions).reduce(
    (a, p) => a + p.quantity * (p.last_price ?? p.entry_price), 0,
  );

  // Walk from capital to the final marked equity, with noise that shrinks
  // to zero at the end so the last point agrees exactly with the holdings.
  const target = cash + finalMtm;
  let noise = 0;
  const equity_curve = dates.map((date, i) => {
    const p = dates.length > 1 ? i / (dates.length - 1) : 1;
    noise = noise * 0.7 + (rand() - 0.5) * opts.capital * 0.012;
    const value = i === dates.length - 1
      ? target
      : opts.capital + (target - opts.capital) * p + noise * (1 - p);
    const inv = i < 3 ? 0 : value - cash;
    return {
      date,
      equity: +value.toFixed(2),
      cash: +(i < 3 ? value : cash).toFixed(2),
      invested_mtm: +inv.toFixed(2),
      num_positions: i < 3 ? 0 : Object.keys(positions).length,
    };
  });

  const pending_buys: PendingBuy[] = (opts.pending ?? []).map(([ticker, ref, qty, reason]) => ({
    ticker, reference_price: ref, quantity: qty, reason,
  }));

  return {
    schema: 'v2',
    cash: +cash.toFixed(2),
    positions,
    pending_buys,
    trades,
    equity_curve,
    [opts.startKey]: dates[0],
    last_rebalance_month: last.slice(0, 7),
  };
}

export const SAMPLE_STATES: Record<'momentum' | 'next50', SleeveState> = {
  momentum: build({
    capital: 100_000, start: '2026-06-01', count: 72, seed: 11, drift: 0.045,
    startKey: 'trial_v2_start_date',
    held: [
      ['BHARTIARTL.NS', 1_882, 'Telecom'], ['BAJFINANCE.NS', 912, 'Financial Services'],
      ['M&M.NS', 3_140, 'Automobile'], ['TRENT.NS', 5_310, 'Consumer Services'],
      ['HDFCBANK.NS', 1_968, 'Banking'], ['SUNPHARMA.NS', 1_702, 'Healthcare'],
      ['TITAN.NS', 3_540, 'Consumer Durables'], ['EICHERMOT.NS', 5_620, 'Automobile'],
      ['HCLTECH.NS', 1_610, 'IT'],
    ],
    sold: [['ADANIENT.NS', 2_480, 2_266, 4, 'Fell out of the top 15 at rebalance']],
  }),
  next50: build({
    capital: 200_000, start: '2026-07-20', count: 40, seed: 29, drift: 0.02,
    startKey: 'trial_start_date', unmarked: 1, deploy: 0.5,
    held: [
      ['BEL.NS', 402, 'Capital Goods'], ['PFC.NS', 468, 'Financial Services'],
      ['INDHOTEL.NS', 781, 'Consumer Services'], ['VBL.NS', 612, 'FMCG'],
      ['LODHA.NS', 1_322, 'Realty'], ['DIVISLAB.NS', 6_140, 'Healthcare'],
    ],
    pending: [
      ['MOTHERSON.NS', 163.2, 81, 'Uptrend (+23% vs SMA)'],
      ['ADANIPOWER.NS', 213.5, 62, 'Uptrend (+16% vs SMA)'],
      ['SIEMENS.NS', 3_954.4, 3, 'Uptrend (+14% vs SMA)'],
      ['HAL.NS', 4_950, 2, 'Uptrend (+13% vs SMA)'],
      ['TVSMOTOR.NS', 4_121.5, 3, 'Uptrend (+11% vs SMA)'],
      ['GAIL.NS', 174.49, 76, 'Uptrend (+6% vs SMA)'],
    ],
    sold: [['IRCTC.NS', 812, 757, 16, 'Closed 3% below its 200-day average']],
  }),
};
